"""empty message

Revision ID: da5e46cc6cf2
Revises: 5355018bc06d
Create Date: 2021-02-07 21:27:10.505813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5e46cc6cf2'
down_revision = '5355018bc06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lckmatch',
    sa.Column('mdate', sa.Text(), nullable=False),
    sa.Column('mtime', sa.Text(), nullable=False),
    sa.Column('team1', sa.Text(), nullable=False),
    sa.Column('team2', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('mdate', 'mtime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lckmatch')
    # ### end Alembic commands ###
